export const WEATHER_UPDATE = 'WEATHER_UPDATE';
export const FORECAST_UPDATE = 'FORECAST_UPDATE';
export const HOURLY_FORECAST = 'HOURLY_FORECAST';
export const THREE_DAY_FORECAST = 'THREE_DAY_FORECAST';
export const WEEKLY_FORECAST = 'WEEKLY_FORECAST';
